### ISSUE TITLE
Update zxing to 3.1.0

### ISSUE THREAD

**Issue by ydeshayes** [appcelerator-modules/ti.barcode#10]
I think the module use the version 1.7 of zxing. Maybe it will be good to update the library ?
zxing https://github.com/zxing/zxing/blob/master/CHANGES

**Comment by marchetb** [comment]
Any news about this update ? Think it's a good idea. This can bring new description possibilities and maybe a custom frameview for the capture ?

**Comment by univers3** [comment]
Oh come on.
Why not update this module?
It have bugs and the pull requests are unseen.
This is very sad because this module is a very important module for a lot of people!

**Comment by linron** [comment]
Please update!

**Comment by m1ga** [comment]
this module is already using "android-core-3.3.1"
