### ISSUE TITLE
ios-1.9.1 - doesn't work

### ISSUE THREAD

**Issue by dwoshadha** [appcelerator-modules/ti.barcode#11]
I wanted to implement iOS version in my app and I tried the sample app it doesn't work at all. This has a issue when rotating the screen. The main issue what I find here is it doesn't scan at all. Could you please help me on this?

Please find the attached pics.
![portrait-200x300](https://cloud.githubusercontent.com/assets/10601025/5987820/736d38de-a95a-11e4-8b5e-8ff3c65c1ba8.png)
![landscape-300x200](https://cloud.githubusercontent.com/assets/10601025/5987823/7f73fb4a-a95a-11e4-9f4c-3fd55776aa5f.png)

**Comment by ulizama** [comment]
I'm having the same issue. Module seems to be able to scan QRCodes only. Everything else is not working.

**Comment by JLCraddock** [comment]
I'm not sure about QRCodes, but UPCA, UPCE, and EAN13 don't scan.

**Comment by tomatlscomm** [comment]
Same problem here.
Tried to build with the sample app, and with an homemade simple app, nothing work.

Landscape mode get crazy, and scanning working erratically (main time not working, sometime working but crazy results, etc...)

**Comment by amwinsauto** [comment]
for iOS, I was able to get v1.9.1 to work....BUT...I had to configure
Barcode.allowRotation = true;

I didn't want to allow rotation (because the results are horrible) so I set Rotation to "false" but then it wouldn't scan at all.  When I set back to "true" then it scanned.

**Comment by tomatlscomm** [comment]
Not for me. Whenever i change allowRotation to false or true it still rotate.
And keep not scanning anything (i'm trying on data matrix or ean)...

**Comment by amwinsauto** [comment]
yes...it still rotates.

What I found out is that if you set it to true, make sure you're in portrait mode when you click to open the scanner, and don't rotate your device, then it appears to scan.

but if you rotate to landscape and then back to portrait...it stops working.

Not saying it is ideal....just trying to help give a (unique) scenario that i have found to (somewhat) work in hopes that helps narrow down where/what needs to be fixed.

oh....and even in this unique scenario....that only appears (at least for me) to only work on iOS handheld devices and doesn't work on iOS Tablets.  :/

**Comment by tomatlscomm** [comment]
Okay ^^
Thank you for the info. So for now, i would say it's pretty far from being usable in a production app :)

**Comment by OutlawMonkey** [comment]
I already got it fixed for iPad.
You have to enable the orientation in the tiapp.xml to handle portrait
and it work just perfect.
Except for one thing.
the cancel button is not working
does anybody have an idea?

**Comment by moizchhatriwala** [comment]
Hi, 
Has any body got success with all the above problems which every one has faced, I am also facing rotation problem and hence I am not able to use it into production build, Please let me know if any one has any of the solution available to resolve the problem.

**Comment by hansemannn** [comment]
Fixed in recent versions of the module. Closing.
