### ISSUE TITLE
frameWidth and frameHeight parameters are ignored

### ISSUE THREAD

**Issue by albert0m** [appcelerator-modules/ti.barcode#118]
Nowhere in the code are assigned.

Fixed it with this:

```
frameWidth = argsDict.optInt("frameWidth", 0);
frameHeight = argsDict.optInt("frameHeight",0);
intent.putExtra(Intents.Scan.WIDTH, frameWidth);
intent.putExtra(Intents.Scan.HEIGHT, frameHeight);
```

**Comment by m1ga** [comment]
isn't it assigned here: https://github.com/appcelerator-modules/ti.barcode/blob/aa7ffe059df720d2d079d0e5494b365b7af7441c/android/src/com/google/zxing/client/android/camera/CameraManager.java#L259-L269

**Comment by albert0m** [comment]
I'm not sure, but if you see the code here:

https://github.com/appcelerator-modules/ti.barcode/blob/d3c7c024bee766803412328bddb65dfa3cd12a68/android/src/com/google/zxing/client/android/CaptureActivity.java#L260

```
if (intent.hasExtra(Intents.Scan.WIDTH) && intent.hasExtra(Intents.Scan.HEIGHT)) {
          int width = intent.getIntExtra(Intents.Scan.WIDTH, 0);
          int height = intent.getIntExtra(Intents.Scan.HEIGHT, 0);
          if (width > 0 && height > 0) {
            cameraManager.setManualFramingRect(width, height);
          }
        }
```

both the extras `Intents.Scan.WIDTH` and `Intents.Scan.HEIGHT` are never set in the module. The fix that I posted in the OP fixed it for me. Before that, any number passed as parameters didn't make any difference.

**Comment by m1ga** [comment]
```
Barcode.capture({
        showCancel: true,
        showRectangle: true,
        frameWidth: 200,
        frameHeight: 100
    });
```
works fine for me with 4.0.3 and Ti SDK 8.3.1.GA

**Comment by albert0m** [comment]
I just realized I was using 4.0.0 binaries prior of updating to 4.0.2 (so that I could compile it), maybe just updating it fixed it? Either ways, it works. Thank you for pointing that out!

**Comment by m1ga** [comment]
it was added again in 4.0.2 (https://github.com/appcelerator-modules/ti.barcode/releases/tag/android-4.0.2)
you can use 4.0.3 too: https://github.com/appcelerator-modules/ti.barcode/releases/tag/android-4.0.3
