### ISSUE TITLE
Using of module overwrites app name on home screen

### ISSUE THREAD

**Issue by AppWerft** [appcelerator-modules/ti.barcode#16]
Hi,
using 2.3.0 of module in sdk3.5.1.GA shows on home screen of android "Barcode Scanner" (text from modules/../res/values/strings.xml) and not my name from tiapp.xml. If I have more then one apps with scanner all apps have this wrong name. In system configuration I can see under apps the right name.

**Comment by hansemannn** [comment]
This should not be an issue anymore.
