### ISSUE TITLE
Overlay is under camera view

### ISSUE THREAD

**Issue by astra909** [appcelerator-modules/ti.barcode#17]
Hi guys,
i´ve an issue with the overlay(Imageview). When i add a cancel button on it, it doesn´t react. It´s only responding on the button, when i lay down the phone on the table.
Seems to be the overlay is under the camera view or something like that.
The Parameter "showCancel" doesn´t work at all with an overlay.
I use your latest version, 1.9.1, project build with Titanium SDK 3.5.1 on an IPhone 5 with IOS 8.3

Hope it can be fixed soon.
Thanks for your help :)

**Comment by annakozy2011** [comment]
I have the same problem, and it started after I upgraded to iOS 8.3

Testing on iPad (iPad-2, iPad-mini), and it only happens on devices. Emulator works fine.

**Comment by annakozy2011** [comment]
Now it´s happening on iPhone 6, iOS 8.4

**Comment by raefa** [comment]
I have not tested overlays but the "showCancel" button fires a "cancelled" event not a "cancel" event as listed in the documentation.

```
Barcode.addEventListener('canceled', function (e) {
  alert("Cancel");
});
```

**Comment by chauf** [comment]
I have the same problem using 5.1.1.GA with iPhone6 and IOS9.2. Any Solution?

**Comment by AceMacLoud** [comment]
Same here, 5.3.0.GA, Xcode 7.3.1

**Comment by hansemannn** [comment]
Fixed in recent versions of the module. Closing.
