### ISSUE TITLE
iOS 8.3, overlay does not respond to clicks.

### ISSUE THREAD

**Issue by annakozy2011** [appcelerator-modules/ti.barcode#19]
I upgraded my iPad to iOS 8.3, and there is a bug - overlay does not respond to any clicks (nor the buttons or anything). 

Any idea how to solve this?

**Comment by annakozy2011** [comment]
PS: it only occurs on device. Simulator works fine.

**Comment by annakozy2011** [comment]
On iPad 8.3 it did work after update of XCode. 

Now the same is happening on iPhone 6 (only) with iOS 8.4

**Comment by beaurushton** [comment]
Yeah overlay is not working on iOS9 :(

**Comment by m1ga** [comment]
any update here?

**Comment by hansemannn** [comment]
Is this issue only happening on iOS8+?

**Comment by hansemannn** [comment]
Hey guys, please try https://github.com/appcelerator-modules/ti.barcode/pull/32 which should resolve this issue, too.

**Comment by hansemannn** [comment]
Closing as duplicate of #41 where it will be addressed.
