### ISSUE TITLE
portrait mode available  on android device ? 

### ISSUE THREAD

**Issue by c1ngular** [appcelerator-modules/ti.barcode#2]
this module only works in landscape mode on android device ,nice working module though!

**Comment by ygbr** [comment]
+1

**Comment by AppWerft** [comment]
+1

**Comment by deepure** [comment]
+1

**Comment by brunogenaro** [comment]
+1

**Comment by macCesar** [comment]
Latest version (2.3.5) and still only landscape capture... Why???

**Comment by hansemannn** [comment]
@m1ga Is this still an issue on Android?

**Comment by m1ga** [comment]
no, it can be change now (will use the phone orientation when it's not set to a fix value)
https://github.com/appcelerator-modules/ti.barcode/pull/56
