### ISSUE TITLE
1D is impossible since OneDMode is set to NO

### ISSUE THREAD

**Issue by MichelBahl** [appcelerator-modules/ti.barcode#20]
The project description "QR **and Barcode** Scanner " is missleading.

It's not possible to scan 1d Barcodes with this module,
because "OneDMode" ist set to NO.
Only minor changes are required to enable 1d Barcode scanning.

TiBarcodeModule.mm->line 233 change  OneDMode:NO to OneDMode: **YES** 
ZXingWidgetController.m->line 498  if (oneDMode) to **if (NO)**

**Comment by hansemannn** [comment]
Cleaning up as part of #52. We will look into supporting this!
