### ISSUE TITLE
Is there a way to scan inside personal view ?

### ISSUE THREAD

**Issue by marchetb** [appcelerator-modules/ti.barcode#21]
I would like to know if it's possible to start scanning inside my tabbed app.
Actually, the camera launch in full screen, and bars are disappearing :/

I see there is "SurfaceView" in android that allow to do this, do you think it's hard to implement ?

Thanks for the answer.

**Comment by m1ga** [comment]
Currently not with this module but there is are alternatives
* https://github.com/mikefogg/SquareCamera 
* https://github.com/acktie/Acktie-Mobile-Android-QR-Reader
that allows you to put the scanner into a view
