### ISSUE TITLE
Add support for arm7 & arm64

### ISSUE THREAD

**Issue by pcflmb** [appcelerator-modules/ti.barcode#23]
With the upgrade to iOS 9 I am no longer able to compile my app, because this module doesn't have support for the new architectures.

**Comment by antongorodezkiy** [comment]
+1

**Comment by m1ga** [comment]
I did it in a fork: https://github.com/m1ga/ti.barcode
Binary is there too. I'm getting one error at the line "UIImage *image = [blob:image];" but was able to compile it and its running on an ipad with ios9. I still need to figure out how to make it work in a landscape app, then I'll create a pull request

**Comment by m1ga** [comment]
pull request https://github.com/appcelerator-modules/ti.barcode/pull/26

**Comment by aiur100** [comment]
I know this is an old thread, and I am using version 2.3.9, but I am wondering if this pull request covers the issue where arm devices symbol not found error  for symbol "__exidx_end" in libti.barcode.so.  I am using 3.5.0.GA, but I had to apply the patch to remove the TrustManager and update the TiVerify jar's and .so files, and I am getting this error.  
`failed: dlopen failed: cannot locate symbol "__exidx_end" referenced by "libti.barcode.so"...
`

**Comment by m1ga** [comment]
Latest iOS version https://github.com/appcelerator-modules/ti.barcode/releases/tag/ios-1.10.1 has support for iOS9+
@aiur100 if you still need help please create an own issue
