### ISSUE TITLE
statusBarStyle of ti.barcode view is always black

### ISSUE THREAD

**Issue by kiafaldorius** [appcelerator-modules/ti.barcode#28]
The status bar text of the Barcode.capture call is always black. I have UIStatusBarStyle in tiapp.xml set to UIStatusBarStyleLightContent but it's still black text when opening the Barcode.capture.

Is there something I can do to get LIGHT_CONTENT on the Barcode.capture window?

**Comment by ashcoding** [comment]
Could you attach a screenshot to illustrate this?

**Comment by kiafaldorius** [comment]
Using SDK version 3.5.1.GA with ti.barcode version 1.9.1 (ios)

```
var Barcode = require('ti.barcode');

var win = Ti.UI.createWindow({
    title: 'Test',
    backgroundColor: '#eee',
    statusBarStyle: Titanium.UI.iPhone.StatusBar.LIGHT_CONTENT
});

var overlay = Ti.UI.createView({
    backgroundColor: 'transparent',
    top: 0, right: 0, bottom: 0, left: 0
});

var header = Ti.UI.createView({
    backgroundColor: '#222',
    top: 0,
    height: 50
});
overlay.add(header);

//win.add(overlay);
win.addEventListener('open', function () {
    Barcode.capture({
        animate: false,
        overlay: overlay,
        showCancel: true,
        showRectangle: true,
        keepOpen: true,
        acceptedFormats: [
            Barcode.FORMAT_QR_CODE
        ]
    });
});

Barcode.addEventListener('success', function (e) {
    Ti.API.info('Barcode: ' + e.result);
});

win.open();
```

This is with the barcode reader activated (on sim, so no camera feed). The top text is there, but it's black on dark background so hard to read. Same issue appears when on the device.

![screen shot 2015-12-09 at 11 00 31 pm](https://cloud.githubusercontent.com/assets/119071/11709088/6ecc508e-9ec9-11e5-9f36-01b9c00f1944.png)

This is what it looks like if the overlay is added directly to the win and no barcode.capture call.

![screen shot 2015-12-09 at 11 05 13 pm](https://cloud.githubusercontent.com/assets/119071/11709087/6ec96536-9ec9-11e5-8c30-6f6dbc4ad1de.png)

**Comment by kiafaldorius** [comment]
To append something else, it is also ignoring UISupportedInterfaceOrientations. I'm forcing only UIInterfaceOrientationPortrait and it works for all the windows I open with Ti.UI.createWindow, but not this Barcode.capture window.

I assume it's the same thing causing this?

**Comment by kiafaldorius** [comment]
@ashcoding Can I get an update please?

**Comment by ashcoding** [comment]
Created a Jira ticket for this issue. https://jira.appcelerator.org/browse/MOD-2183

**Comment by kiafaldorius** [comment]
Happy New Years!

So I don't have permission to comment on the jira and it looks like no progress has been made. Can I ask for a poke on the task? I understand it was the holidays, but I was at least hoping it was triaged at least.

PS. It has "planned end" set to december 21?

**Comment by ashcoding** [comment]
@kiafaldorius Happy new year!

For prodding and poking (:point_right:), it's best to prod and poke inside the jira ticket. That's where more attention is given (as compared to github issues). :smile: 

CC: @hansemannn if you have time, you could check this out.

**Comment by kiafaldorius** [comment]
That's what I was trying to say above...I can't comment on the JIRA ticket. I'm logged in and watching the ticket (Watchers: 2), but no way to comment.

**Comment by hansemannn** [comment]
You're right! MOD namespaces are restricted as far as I know. I will check the issue this week.

**Comment by kiafaldorius** [comment]
Thank you so much! Happy New Year =]

**Comment by hansemannn** [comment]
Hi @kiafaldorius, just got it fixed, but the overlay looks unresponsive. Need to take a closer look before.

 ![Example](http://abload.de/img/img_79606zb0z.png)

**Comment by hansemannn** [comment]
Hey guys, please try https://github.com/appcelerator-modules/ti.barcode/pull/32 which should resolve this issue.

**Comment by kiafaldorius** [comment]
Hiya,

Can I also get the same inherit fix for the window orientation (Ti.UI.Window#orientationModes) please? (Locked orientation using UIInterfaceOrientationPortrait but the window doesn't obey the global rules.)

The header seems to be fixed on sim and phone. I assume orientation is a similar fix?

Thanks!

**Comment by kiafaldorius** [comment]
@hansemannn Can you take a look at the UIInterfaceOrientationPortrait please?

Or if you can show me how to set it up, I'll take a shot at it...I assume it's something similar to what you did for the other property?

**Comment by hansemannn** [comment]
Please file an own ticket for that feature, thank you!

**Comment by kiafaldorius** [comment]
@hansemannn #34 

Thanks!

Can close this one once the pull request gets merged, it works!
