### ISSUE TITLE
Update zxing to 3.2.1

### ISSUE THREAD

**Issue by univers3** [appcelerator-modules/ti.barcode#29]
Why not update this module to the new version of zxing?
It have a lot of new features and bug fixes!

**Comment by macCesar** [comment]
+1

**Comment by univers3** [comment]
Yeah!
This module sucks with the current version of zxing.
Anyone in titanium/appcelerator staff that can point out this situation?
Thanks

**Comment by hansemannn** [comment]
We are using latest these days, closing!

**Comment by univers3** [comment]
Thanks for the reply, but already switched to React Native!

**Comment by hansemannn** [comment]
Good lord, have fun :-).
