### ISSUE TITLE
Custom Rectangle SIZE

### ISSUE THREAD

**Issue by italoc** [appcelerator-modules/ti.barcode#31]
there is a method to customize the dimension of rectangle in overlay during barcode scanning?

now the dimension if the screen in not so higher is good, but with big monitor (S5,S6,NEXUS5) the rectangle is too little...

thank you

**Comment by danny005** [comment]
Very interested in this too.

**Comment by danny005** [comment]
Looks like there is a fork that supports frameWidth und frameHeight?

https://github.com/m1ga/ti.barcode

**Comment by MushoodMunir** [comment]
@danny005  Have you tried it? Does it work?

**Comment by m1ga** [comment]
Yes it does. Feel free to test it: https://github.com/m1ga/ti.barcode/releases/tag/3.1.0
**Careful:**  Switch on/off torch and front camera is currently not supported

```javscript
var Barcode = require('ti.barcode');

var win = Ti.UI.createWindow({
    backgroundColor: 'white',
    layout: "vertical"
});

var tf_w = Ti.UI.createTextField({
    value: "100",
    width: Ti.UI.FILL,
    borderColor: "#000",
    borderWidth: 1,
    color: "#000"
});
var tf_h = Ti.UI.createTextField({
    value: "100",
    width: Ti.UI.FILL,
    borderColor: "#000",
    borderWidth: 1,
    color: "#000"
});
var scanCode = Ti.UI.createButton({
    title: 'Scan Code',
    width: 150,
    height: 60,
    top: 20
});
scanCode.addEventListener('click', function() {
    Barcode.capture({
        showCancel: true,
        showRectangle: true,
        frameWidth: parseInt(tf_w.value),
        frameHeight: parseInt(tf_h.value)
    });
});
win.add(Ti.UI.createLabel({
    text: "Width:",color:"#000"
}));
win.add(tf_w);
win.add(Ti.UI.createLabel({
    text: "Height:",color:"#000"
}));
win.add(tf_h);
win.add(scanCode);

win.open();
```

**Comment by danny005** [comment]
Hi m1ga, works fine with the custom frame size, thanks. Is there any reason, why torch and front camera is not supported in your branch?

**Comment by m1ga** [comment]
Torch is working now, only switching to the front camera (and fixing some bugs) is on my todo list. The xzing code has changed so the old module code wasn't working anymore

**Comment by danny005** [comment]
Very cool. Where can I find the version with the working torch?

**Comment by m1ga** [comment]
you can use it with the latest release now:
https://github.com/appcelerator-modules/ti.barcode/releases/tag/android-3.1.0
