### ISSUE TITLE
ti.barcode ignores global orientation settings in tiapp.xml

### ISSUE THREAD

**Issue by kiafaldorius** [appcelerator-modules/ti.barcode#34]
UISupportedInterfaceOrientations is set to only UIInterfaceOrientationPortrait, but ti.barcode's window ignores it.

**Comment by kiafaldorius** [comment]
@ashcoding can I get this created as a JIRA so @hansemannn or someone else can officially look into it?

Thanks!

**Comment by ashcoding** [comment]
@kiafaldorius Are you able to create this in the TIMOB section in JIRA? I believe in that section, you can comment on it as well? (Correct me if I'm wrong)

**Comment by kiafaldorius** [comment]
@ashcoding I am *NOT* able to create tickets nor comment on them. The whole MOD namespace is restricted. I can only watch the tickets.

**Comment by ashcoding** [comment]
What I meant was instead of the MOD namespace, you could try the TIMOB namespace.

**Comment by kiafaldorius** [comment]
I can only create tickets in the following projects:

* Appcelerator Studio (AC)
* Aptana Studio (APSTUD)
* Titanium Community (TC)
* Training Curriculum & Certification (TCC)

**Comment by ashcoding** [comment]
Got it. Created ticket https://jira.appcelerator.org/browse/MOD-2190 for this.

I think another way a ticket could be created in Titanium Community (TC). We could then address it there and move it to the MOD namespace. This is if you have future issues to create. :+1:

**Comment by kiafaldorius** [comment]
Ok, I'll do that next time. Thanks!

Hopefully this is the last one for a while though.

**Comment by ashcoding** [comment]
Welcome!

**Comment by chauf** [comment]
I have the same Issue.
By the way: The setting "allowRotation" is miss leading because it says if the barcode is allowed to be rotated or not and not if the view of the module will rotate or not.

**Comment by hansemannn** [comment]
[This commit](https://github.com/appcelerator-modules/ti.barcode/commit/f02103b2a17a36e5356d5b612dd3cc8a0ac24c96) should fix the issue, can you test the full PR on this issue?

**Comment by chauf** [comment]
Hi, thanks for that quick fix but unfortunately after this changes the hole app closes after calling Barcode.capture(...

**Comment by kiafaldorius** [comment]
@chauf confirmed crash. It happens to me also. No stack trace or anything.

**Comment by hansemannn** [comment]
Ok, I will further investigate the issue and ping back here!

**Comment by kiafaldorius** [comment]
Thanks!

**Comment by kiafaldorius** [comment]
@hansemannn How's the investigation? Any updates?

**Comment by hansemannn** [comment]
Yes. The latest commit makes it possible to use the parent orientation when opening the scanner. The orientation change does not work, yet and needs some more attention.
