### ISSUE TITLE
camara does not show up clearly

### ISSUE THREAD

**Issue by levieraf** [appcelerator-modules/ti.barcode#39]
When the reader is activated , the camera does not focus properly clearly, it is not crisp as it should be to activate the camera. For example using Barcode Scanner does work fine, show up correctly! but for some reason with Ti.Barcode no. Any Idea?

I am using titanium 5.1.1.GA
On android 5.1.1

Thanks!.

**Comment by levieraf** [comment]
I found the problem, I am using a samsung J7 which does have more size screen, the library is wrote to work with the size screen:


```
private static final int MIN_PREVIEW_PIXELS = 320 * 240; // small screen
private static final int MAX_PREVIEW_PIXELS = 800 * 480; // large/HD screen
```

I saw that the last commit was 3 years, now we have smartphone with more resolution. I think that this values must be part like parameter to change depends of the screen of phone used.

**Comment by univers3** [comment]
Totally agree with you @levieraf !

**Comment by levieraf** [comment]
Yes, I could resolve the issue using other ti.barcode:

[https://github.com/Exygy/Titanium-Ti.Barcode](https://github.com/Exygy/Titanium-Ti.Barcode)

He did the change for devices for more resolution, work good at the moment with the functionality that I need.

That please, do not wait much time to update this!

**Comment by m1ga** [comment]
https://github.com/appcelerator-modules/ti.barcode/releases/tag/android-3.1.0
will try to get the best resolution  automatically
