### ISSUE TITLE
[Android] Camera screen is not showing.

### ISSUE THREAD

**Issue by jasonchongbinary** [appcelerator-modules/ti.barcode#40]
The first time you use the bar code scan feature instead of seeing the camera image a black screen is shown.
Pressing back seems to not do anything, putting the app in background and then bring forward still showed the black screen,  closing the app and reopening still shows the black screen when scan bar code is selected again. I can’t be sure but I think rotating the screen or swiping down the top menu when the black screen was shown caused it to then show the what’s “New in version 4.0:” screen for the bar code scanner. Once you press DONE button at the bottom the camera image is shown and you can scan. After then selecting scan code always brings up the camera. So it looks like the display of the scanner “whats new” screen is causing issues.

**Comment by m1ga** [comment]
The "New screen" (and the other zxing related views) shouldn't be displayed in the latest android version: https://github.com/appcelerator-modules/ti.barcode/releases/tag/android-3.1.0
it should go straight into camera view
