### ISSUE TITLE
Cancel button not respond to click ios?

### ISSUE THREAD

**Issue by MushoodMunir** [appcelerator-modules/ti.barcode#41]
Cancel button not working in both cases on ios. Either i use overlay and add my own custom cancel button or use showCancel property with true value. Both cases not able to close Barcode scan view. Working just on simulator but not on device tested on iPod having iOS 8.3. I tested with latest code and module 1.10.0. As @hansemannn respond on issue #19. 

> Hey guys, please try #32 which should resolve this issue, too.

**Comment by joanxtb** [comment]
Is this case solved ? I'm still having issues with adding custom buttons as an overlay. usually the cancel action crashes the app (which is much worst)

**Comment by joanxtb** [comment]
Ok, just so you know: this is a problem on Titanium SDK >= 6.1.1

**Comment by hansemannn** [comment]
Scheduled for next iOS patch-release!

**Comment by chmiiller** [comment]
Maybe it is related to this line: https://github.com/appcelerator-modules/ti.barcode/blob/cd1fa018e31a10c758ec660f81c63ca22ed95886/ios/Classes/TiBarcodeModule.mm#L231
I really have the feeling that the "device is busy" and that's why it doesn't work. What do you think @hansemannn ?

**Comment by hansemannn** [comment]
Are you getting that error? It would mean that the old instance is still active and cleaning up. Let me do a quick troubleshooting this week.

**Comment by chmiiller** [comment]
Yes I'm using the last version 1.10.1 and it works some times. It is hard to show you what's happening, but sometimes it doesn't work. Are you trying on device?
Can you try with an overlay and a "close" button? Seems that the "click" event is never fired from the overlay =/

**Comment by chmiiller** [comment]
So this issue could be closed since everything works correctly

**Comment by hansemannn** [comment]
Thanks!
