### ISSUE TITLE
Run module 1.9.0 

### ISSUE THREAD

**Issue by MahmoudElmoghazy** [appcelerator-modules/ti.barcode#5]
hi man now i have a problem while using the module in ios when i run the module 1.9.0 on titanium sdk 3.5.0 RC it give me this bug
[ERROR] :  *\* BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :   Ld build/Debug-iphoneos/qr\ reader.app/qr\ reader normal armv7
[ERROR] :  (1 failure)

can u help me to fix this bug

**Comment by hansemannn** [comment]
This is not an issue anymore, closing!
