### ISSUE TITLE
How to support both orientations landscape and portrait for Android?

### ISSUE THREAD

**Issue by MushoodMunir** [appcelerator-modules/ti.barcode#51]
How can I support both orientations for Android app? As current version only scans barcode in landscape mode. What changes I have to make to work it in both orientations. I want it to relayout scan view when user change it's device orientation. Can somebody help me out how to achieve this?

**Comment by chmiiller** [comment]
Any news on this?

**Comment by m1ga** [comment]
Not yet, sorry. The current version is still set to landscape (https://github.com/appcelerator-modules/ti.barcode/blob/master/android/timodule.xml#L10). I'll put it on my todo list to check what need to be changed

**Comment by chmiiller** [comment]
That would be awesome! Thanks!

**Comment by m1ga** [comment]
@chmiiller quick fix: change the line in the timodule.xml to
`android:screenOrientation="fullSensor"`
and it will open in the same orientation you are holding the phone while opening the scanner.

**Comment by m1ga** [comment]
Please test this preview version: https://github.com/m1ga/ti.barcode/releases/tag/android-3.1.1

**Comment by chmiiller** [comment]
It really works! Much better like this. We can PR, merge and close this ticket

**Comment by m1ga** [comment]
merged!
