### ISSUE TITLE
iOS doesn't read 1D barcode

### ISSUE THREAD

**Issue by macasfaj** [appcelerator-modules/ti.barcode#52]
iOS version only reads QR code, not 1D barcode.

Any help with that?

**Comment by CraddockJ** [comment]
I'm having issues with this as well. It focuses, but the capture event never happens, no matter how clear the picture.

**Comment by brentonhouse** [comment]
I am seeing this issue as well with the latest version:  1.10.1

**Comment by mlcunha** [comment]
I'm having issues with this as well. Do you know when would you solve this problem?

**Comment by hansemannn** [comment]
As discussed in #20 (thanks @michelbahl), it could be enabled quite easily via 2 changes in the module source. Contributions welcome!

**Comment by hansemannn** [comment]
The following 1D barcodes are supported now:
- Code 128
- EAN-8
- EAN-13
- UPC-A
- UPC-E
- Code 39
- Code 93

**Comment by marconealberto** [comment]
just downloaded the latest version (2.0.4) and created an empty project and it doesn't scan any 1D barcodes (we use the Code 39). It works instantly with QRcodes. 

This is the code:

```
var Barcode = require('ti.barcode');

function barCodeHandler(data) {
	console.log("e",data);
};

Barcode.addEventListener('success', barCodeHandler);
Barcode.capture({
		keepOpen : true
});
```
the handler is never called.

The app is running on 7.5.0.GA on a iOS 12 device.
