### ISSUE TITLE
What is "animated"?

### ISSUE THREAD

**Issue by FidelCorrales** [appcelerator-modules/ti.barcode#58]
Hi good day I hope Someone can help please. In the Barcode.capture function there is a parameter: animated, but I don't know what it does.
I put it false, i put it true but I don't notice a difference. 
In the documentation says: "animate[boolean]: Indicates if the device should animate between the current activity and the camera activity when the current activity is in a different orientation than the camera. Default is true". But I don't understand what it does. Can You help me please! I'm from Mexico and my native language is Español.
Thanks

**Comment by m1ga** [comment]
On Android it will set the `FLAG_ACTIVITY_NO_ANIMATION` flag when it starts the activity:
https://github.com/appcelerator-modules/ti.barcode/blob/cd1fa018e31a10c758ec660f81c63ca22ed95886/android/src/ti/barcode/BarcodeModule.java#L276

you will see the camera window sliding in from the bottom or not when you set it to true or false. It is not a big animation, just the standard "open window" from Android.

Try to set it to true/false and open the window and see the difference for yourself. If you don't have any performance issues just keep it `true` so it will look a bit smoother when the window opens

**Comment by FidelCorrales** [comment]
Thanks! :)

Enviado desde mi iPhone
