### ISSUE TITLE
Android Menu Button / iOS Overlay Layout

### ISSUE THREAD

**Issue by walkthelot** [appcelerator-modules/ti.barcode#64]
When pressing the Android menu button on an Android device, the host app crashes. allowMenu seems to have no effect.

In iOS, the overlay view, no matter what you do, is not able to be formatted for width and other view layout properties. No matter what you do, the view (via createView) always aligns upper left and it is impossible to have it's width or height fill the parent window. Everything in this regard works as expected in Android.

**Comment by m1ga** [comment]
Could you please provide some test code for both problems. Would make it quicker to test it

**Comment by kenrucker** [comment]
Working code on Android for proper layout. If I do much more it starts falling apart. 

            var overlay = Ti.UI.createView({
                backgroundColor: 'transparent',
                width:Titanium.UI.FILL,
                height:Titanium.UI.SIZE
            });

            var ledButton = Ti.UI.createButton({
                title: 'toggle led', textAlign: 'center',
                bottom: '10dp',
                left: '10dp',
                height: '39dp',
                width: '125dp',                
                borderRadius: 0,
                borderWidth:'1dp',
                font:{fontSize:'15dp'},
                textAlign:'center',
                color:'white'
            });
            ledButton.addEventListener('click', function () {
                Barcode.useLED = !Barcode.useLED;
                ledButton.title = Barcode.useLED ? 'led is on' : 'led is off';
            });
            overlay.add(ledButton);

            var cancelButton = Ti.UI.createButton({
                title: 'cancel',
                bottom: '10dp',
                right: '10dp',
                height: '39dp',
                width: '125dp',              
                borderRadius: 0,
                borderWidth:'1dp',
                font:{fontSize:'15dp'},
                textAlign:'center',
                color:'white'
            });
            cancelButton.addEventListener('click', function () {
                Barcode.cancel();
            });
            overlay.add(cancelButton);

With this config, in iOS, everything just gets tossed on top of each other on the far upper left of the screen.

**Comment by kenrucker** [comment]
Standby for better test code...

**Comment by kenrucker** [comment]
var Barcode = require('ti.barcode');
Barcode.allowRotation = true;
Barcode.displayedMessage = ' ';
Barcode.allowMenu = false;
Barcode.allowInstructions = false;
Barcode.useLED = false;

var buttonScan = Titanium.UI.createButton({
    textAlign:'center',
    title:'scan barcode or qrcode'
});
mySampleView.add(buttonScan);

var checkCameraPermissions = function(callback) {
    
    if (Ti.Media.hasCameraPermissions()) {
        callback(true);
    } else { 
        Ti.Media.requestCameraPermissions(function(e) {
             if (e.success === true) {
                 callback(true);
             } else {
                 callback(false);
             }
        });
    }
};    

buttonScanVIN.addEventListener('click',function() {

    checkCameraPermissions(function(returnedDataVIN) {

        if (returnedDataVIN == true) {

            var overlay = Ti.UI.createView({
                backgroundColor: 'transparent',
                width:Titanium.UI.FILL,
                height:Titanium.UI.SIZE
            });

            var ledButton = Ti.UI.createButton({
                title: 'toggle led', textAlign: 'center',
                bottom: '10dp',
                left: '10dp',
                height: '39dp',
                width: '125dp',                
                borderRadius: 0,
                borderWidth:'1dp',
                font:{fontSize:'15dp'},
                textAlign:'center'
            });
            ledButton.addEventListener('click', function () {
                Barcode.useLED = !Barcode.useLED;
                ledButton.title = Barcode.useLED ? 'led is on' : 'led is off';
            });
            overlay.add(ledButton);

            var cancelButton = Ti.UI.createButton({
                title: 'cancel',
                bottom: '10dp',
                right: '10dp',
                height: '39dp',
                width: '125dp',              
                borderRadius: 0,
                borderWidth:'1dp',
                font:{fontSize:'15dp'},
                textAlign:'center'
            });
            cancelButton.addEventListener('click', function () {
                Barcode.cancel();
            });
            overlay.add(cancelButton);
           
            Barcode.addEventListener('error', function (e) {
                Ti.UI.createAlertDialog({ cancel: 0, buttonNames: ['OK'], title:'Scanning Error', message:'Error while scanning. Error: ' + e.message}).show();
            });

            Barcode.addEventListener('cancel', function (e) {
                Ti.API.info('Cancel received');
            });

            Barcode.addEventListener('success', function (e) {
                if (e != undefined && e.result != undefined) {                    
                    var scanResult = right(e.result.toUpperCase().trim(), 17);                    
                    Barcode.cancel();            
                    alert(e.format + ' barcode ' + scanResult);                    
                }
            });
                                    
            Barcode.capture({
                overlay: overlay,
                showCancel: false,
                showRectangle: true,
                keepOpen: false,                
                acceptedFormats: [
                    Barcode.FORMAT_QR_CODE,
                    Barcode.FORMAT_CODE_39
                ]
            });
                        
        } else {
            Ti.UI.createAlertDialog({ cancel: 0, buttonNames: ['OK'], title:'Permission Not Granted', message:'You have not granted the app the needed permissions to access your camera and/or device storage.\n\nPlease review the app permissions within your device Settings in order to grant the needed permissions.'}).show();
        }
    });                            
});

**Comment by m1ga** [comment]
I don't have a menu button so I only can test it via ` adb shell input keyevent 1` and don't see a crash there.

**Comment by kenrucker** [comment]
Understood. Maybe not a huge issue since most devices no longer
      have a dedicated menu button.
    
    Ken Rucker
      WalkTheLot.com
      Inc.
      ken@walkthelot.com
      904/600.5071 Ext. 10
      Support: 904/600.5071 | Sales/Pre-Sales Support: 800/615.9981
      Check out our YouTube
          Channel
    
    On 2/4/2018 10:38 AM, Michael Gangolf
      wrote:
    
    
      I don't have a menu button so I only can test it via adb
          shell input keyevent 1 and don't see a crash there.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/appcelerator-modules/ti.barcode","title":"appcelerator-modules/ti.barcode","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/appcelerator-modules/ti.barcode"}},"updates":{"snippets":[{"icon":"PERSON","message":"@m1ga in #64: I don't have a menu button so I only can test it via ` adb shell input keyevent 1` and don't see a crash there."}],"action":{"name":"View Issue","url":"https://github.com/appcelerator-modules/ti.barcode/issues/64#issuecomment-362916045"}}}
    
    
  

	
        
		Virus-free. www.avg.com

**Comment by m1ga** [comment]
@kenrucker just had to implement Ti.Barcode with an overlay on iOS (iPhone) and it is not visible as you already mentioned. 
```javascript
var Barcode = require('ti.barcode');
		Barcode.allowMenu = false;
		Barcode.allowInstructions = false;
		Barcode.displayedMessage = ' ';
		Barcode.allowRotation = true;

		var overlay = Ti.UI.createView({
			backgroundColor: 'transparent',
			top: 0,
			right: 0,
			bottom: 0,
			left: 0,
			width: Ti.UI.FILL,
			height: Ti.UI.FILL,
		});
		var lbl = Ti.UI.createLabel({
			bottom: 10,
			left: 10,
			right: 10,
			textAlign: Ti.UI.TEXT_ALIGNMENT_CENTER,
			text: "text",
			color: "#fff",
			backgroundColor: "transparent",
			touchEnabled: false
		});
		overlay.add(lbl);
		var cancelButton = Ti.UI.createButton({
			title: 'X',
			top: 0,
			right: 0,
			width: 30,
			right: 30,
			backgroundColor: "transparent",
			color: "#fff"
		});
		cancelButton.addEventListener('click', function() {
			Barcode.cancel();
		});
		overlay.add(cancelButton);

		Barcode.capture({
			animate: true,
			overlay: overlay,
			showCancel: false,
			showRectangle: true,
			keepOpen: false,
		});
		Barcode.addEventListener('success', function(e) {
			Ti.API.info('Success called with barcode: ' + e.result + " " + e.format);
		});
```

working fine on Android. 
Also it looks like the rotation bug (https://jira.appcelerator.org/browse/MOD-1909) is back again too

**Comment by hansemannn** [comment]
Fixed in recent versions of the module. Closing.
