### ISSUE TITLE
Barcode.setUseLED crashes with NullPointerException on Android

### ISSUE THREAD

**Issue by linron** [appcelerator-modules/ti.barcode#68]
[WARN] :   W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
[WARN] :   W/System.err: 	at android.preference.PreferenceManager.getDefaultSharedPreferencesName(PreferenceManager.java:498)
[WARN] :   W/System.err: 	at android.preference.PreferenceManager.getDefaultSharedPreferences(PreferenceManager.java:487)
[WARN] :   W/System.err: 	at com.google.zxing.client.android.camera.CameraConfigurationManager.setTorch(CameraConfigurationManager.java:239)
[WARN] :   W/System.err: 	at ti.barcode.BarcodeModule.setUseLED(BarcodeModule.java:155)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.runtime.v8.V8Object.nativeFireEvent(Native Method)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.runtime.v8.V8Object.fireEvent(V8Object.java:63)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.KrollProxy.doFireEvent(KrollProxy.java:962)
[WARN] :   W/System.err: 	at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1186)
[WARN] :   W/System.err: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleMessage(TiViewProxy.java:394)
[WARN] :   W/System.err: 	at android.os.Handler.dispatchMessage(Handler.java:98)
[WARN] :   W/System.err: 	at android.os.Looper.loop(Looper.java:154)
[WARN] :   W/System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
[WARN] :   W/System.err: 	at java.lang.reflect.Method.invoke(Native Method)
[WARN] :   W/System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
[WARN] :   W/System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by m1ga** [comment]
Which Axway SDK are you using? Which mobile phone (brand, Android version, does it have a backlight LED) and can you provide some test code?

**Comment by linron** [comment]
I am using SDK 7.1.1. the phone is an galaxy s2. The backlight is also working if i use the camera view. 

The code is from the sample app:
ledButton.addEventListener('click', function () {
    try {
    	Barcode.setUseLED(!Barcode.getUseLED());
    	ledButton.title = Barcode.getUseLED() ? 'Off' : 'On';
    } catch (e) {
    	// Light not working
    }
});

**Comment by m1ga** [comment]
@linron can you please try this build: https://migaweb.de/ti.barcode-android-4.0.1.zip
I've added a null-check so it shouldn't throw the error.

**Comment by m1ga** [comment]
@linron could you already test the bugfix version?

**Comment by hansemannn** [comment]
Thanks @m1ga !
