### ISSUE TITLE
[Request] Add a delay before active the scan

### ISSUE THREAD

**Issue by nicolomonili** [appcelerator-modules/ti.barcode#72]
I'm testing the module on iOS. It works very well (to well). _I have enabled only the Barcode.FORMAT_QR_CODE._
In fact, very often if i start scanning with the camera in front of a qrcode, this is recognized immediately, not even allowing the view-overlay to open (or the view-overlay opens for a few milliseconds). 

Would not it be useful to add a delay (in milliseconds?) before activating the scan? That is, open the camera, but enable scanning after the set delay.

Thank you

**Comment by m1ga** [comment]
I'm not sure why you would add a delay if it works so fast. If you have the QR code already in front of camera and it scans it already the user is happy :)

**Comment by hansemannn** [comment]
Yep, this should not be implemented as part of the module. You could should a custom window before actually showing the camera if really necessary, but even natively (using the camera in iOS 11+), it detects asap without any delay, so we should follow that convention.
