### ISSUE TITLE
QR Code reading on iOS suboptimal

### ISSUE THREAD

**Issue by linron** [appcelerator-modules/ti.barcode#73]
If i am trying to scan a QR code on iOS it is very hard to find the correct distance with the camera. Also it takes quite long before the QR Code is detected. I have found out that you have to come very close before the code is detected - this on the other hand causes problems with the auto focus of the camera. If have tested this with an iphone 5c and an iphone 7.

Looking forward to your feedback!

**Comment by hansemannn** [comment]
The used ZXing library is for basic QR- and barcode-detection. For apps that require more fine granular usages, we recommend the Scandit SDK, which offers full Titanium support as well.

**Comment by linron** [comment]
Hi! Thanks for your answer! I am not sure if this is a library problem. The camera resolution on the QR code view is much lower than the resolution of the standard camera view. This is the reason why you have to come very close to the QR code to get the right resolution. Maybe it is also a focus setting for the camera. 

Any help on this would be great.
