### ISSUE TITLE
Android : What permissions are required to use the ti.barcode module?

### ISSUE THREAD

**Issue by nicolomonili** [appcelerator-modules/ti.barcode#74]
On iOS i have no problem, i only ask the permission for the camera

 ```
if (Ti.Media.hasCameraPermissions()) {
    openQrcode();
} else {
    Ti.Media.requestCameraPermissions(function(e) {
        if (e.success) {
            openQrcode();
        } else {

            var tempmessage = "Hai negato l'accesso alla fotocamera del dispositivo inibendone la possibilità di scansionare i QR code.\n\n";
            if (isAndroid) {
                tempmessage += "Naviga in Impostazioni / App / " + Ti.App.name + " / Autorizzazioni e consenti l'accesso alla fotocamera.";
            } else {
                tempmessage += "Naviga in Impostazioni / Privacy / Fotocamera / " + Ti.App.name + " e consenti l'accesso alla fotocamera.";
            }

            var alertDialog = Ti.UI.createAlertDialog({
                title: "Attenzione",
                message: tempmessage,
                buttonNames: ["Ok"]
            });
            alertDialog.show();

        }
    });
}

function openQrcode() {
    Barcode.capture({
        animate: false,
        overlay: overlayQrcode,
        showCancel: false,
        showRectangle: true,
        keepOpen: false,
        acceptedFormats: [
            Barcode.FORMAT_QR_CODE
        ]
    });
}       
```
But now on Android i think i have some problems with the permission... For Android i use the same code above, plus this on the tiapp.xml

```
<android xmlns:android="http://schemas.android.com/apk/res/android">
        <manifest>
            <application android:theme="@style/Theme.AppCompat.Translucent.NoTitleBar.Fullscreen"/>
            <application android:debuggable="false"/>
            <uses-sdk android:minSdkVersion="16" android:targetSdkVersion="23"/>
            <uses-permission android:name="android.permission.CAMERA"/>  
        </manifest>
</android>   
```
On Android , when i have to open the camera, two permission requests are displayed 

![schermata 2018-07-20 alle 10 50 24](https://user-images.githubusercontent.com/2778813/42993215-1fe4c6cc-8c0b-11e8-843d-68985a73e54f.png)
![schermata 2018-07-20 alle 10 50 30](https://user-images.githubusercontent.com/2778813/42993220-23116986-8c0b-11e8-98e7-063a51520258.png)

After the permissions are accepted, the function `openQrcode()` is called, and the app crashes.

![schermata 2018-07-20 alle 10 50 35](https://user-images.githubusercontent.com/2778813/42993227-26bb0132-8c0b-11e8-8617-93b9342645bc.png)

**Comment by m1ga** [comment]
check this example https://github.com/appcelerator-modules/ti.barcode/issues/59#issuecomment-403747604
You only need the normal Android camera permissions, like you would use to display and use the normal camera in Titanium. So you can check the official documentation too.

If you check your app permission on your phone it should allow storage and camera in order to work.
Do you have any error message in the log?

**Comment by nicolomonili** [comment]
This is the actual permissions of the app

![schermata 2018-07-20 alle 11 28 16](https://user-images.githubusercontent.com/2778813/42995043-21e9d57a-8c10-11e8-9406-503b73014135.png)

Unfortunately there is no log on the console

**Comment by m1ga** [comment]
check `adb logcat` there should be a lot of output and stop it right after the crash to see if you can spot something. That would help alot. Permissions should be fine.

**Comment by hansemannn** [comment]
Something is wrong with your overlay:
> Unable to start activity ComponentInfo{com.-.-/com.google.zxing.client.android.CaptureActivity}: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.

**Comment by hansemannn** [comment]
Please refer to general help via Slack or StackOverflow. This issue tracker is focussed on module bugs, which this one isn't.

**Comment by nicolomonili** [comment]
Incredible ... I found what caused the crash ... it's the property **borderColor** of the view overlayQrcode...
