### ISSUE TITLE
iOS - 2.0.1 : the property displayedMessage is not recognized

### ISSUE THREAD

**Issue by nicolomonili** [appcelerator-modules/ti.barcode#79]
With the update **2.0.1**, my custom **displayedMessage** string it is no longer displayed.
The default message is displayed: "_Place the barcode inside the rectangle to scan it._"

**Comment by hansemannn** [comment]
cc @vijaysingh-axway

**Comment by vijaysingh-axway** [comment]
@nicolomonili Was it working in 2.0.0?

**Comment by nicolomonili** [comment]
No.

**Comment by vijaysingh-axway** [comment]
@nicolomonili Thanks for reporting the issue. I have created ticket https://jira.appcelerator.org/browse/MOD-2453 for same. Thanks!

**Comment by nicolomonili** [comment]
Version [2.0.2](https://github.com/appcelerator-modules/ti.barcode/releases/tag/ios-2.0.2) solves the issue
