### ISSUE TITLE
XCode 10 and 7.4.0GA

### ISSUE THREAD

**Issue by Wingee** [appcelerator-modules/ti.barcode#86]
I've got an app that I'm building with SDK 7.4.0 GA and on iOS the build will fail it I add the ti.barcode module.

I get the following error:

[ERROR] :  ** BUILD FAILED **
[ERROR] :  The following build commands failed:
[ERROR] :  	Ld /Users/engweichua/Documents/Appcelerator_Studio_Workspace/Test\ Project/build/iphone/build/Products/Debug-iphonesimulator/Test\ Project.app/Test\ Project normal x86_64
[ERROR] :  (1 failure)

I've tried the latest version 2.0.2 but i still get the same error above.

Any ideas why?

**Comment by hansemannn** [comment]
See #85  :)

**Comment by hansemannn** [comment]
-> https://github.com/appcelerator-modules/ti.barcode/releases/tag/ios-v2.0.3
