### ISSUE TITLE
Android and 7.4.0.GA

### ISSUE THREAD

**Issue by linron** [appcelerator-modules/ti.barcode#87]
The ti.barcode module fails with SDK 7.4.0

[ERROR] :  Failed to run dexer:
[ERROR] :  
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/media/ExifInterface;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/media/ExifInterface$1;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/media/ExifInterface$ByteOrderedDataInputStream;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/media/ExifInterface$ByteOrderedDataOutputStream;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/media/ExifInterface$ExifAttribute;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/media/ExifInterface$ExifTag;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/media/ExifInterface$IfdType;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Landroid/support/media/ExifInterface$Rational;
[ERROR] :  8 errors; aborting

**Comment by linron** [comment]
What part of the tiapp.xml?

<android xmlns:android="http://schemas.android.com/apk/res/android">
        <manifest android:versionCode="8">
            <application android:theme="@style/appcelerator"/>
            <uses-sdk android:targetSdkVersion="26"/>
            <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
            <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
            <uses-permission android:name="android.permission.MOUNT_UNMOUNT_FILESYSTEMS"/>
            <uses-permission android:name="android.permission.CAMERA"/>
            <uses-feature android:name="android.hardware.camera"/>
        </manifest>
    </android>
    <property name="ti.android.threadstacksize" type="int">131072</property>
    <property name="ti.android.httpclient.maxbuffersize" type="int">131072</property>
    <modules>
        <module platform="android">ti.barcode</module>
        <module platform="iphone">ti.barcode</module>
        <module platform="commonjs">ti.cloud</module>
        <module platform="iphone">ti.imagefactory</module>
        <module platform="android">ti.imagefactory</module>
    </modules>

**Comment by linron** [comment]
Yes the latest release. Thanks!

**Comment by m1ga** [comment]
Works fine without a compile or runtime error:
```
<modules>
      <module>ti.barcode</module>
      <module>ti.imagefactory</module>
  </modules>
<sdk-version>7.4.0.GA</sdk-version>
```

```
Operating System
  Name                        = Mac OS X
  Version                     = 10.13.6
  Architecture                = 64bit
  # CPUs                      = 8
  Memory                      = 16.0GB

Node.js
  Node.js Version             = 8.10.0
  npm Version                 = 5.6.0

Appcelerator CLI
  Installer                   = 4.2.13
  Core Package                = 7.0.6

Titanium CLI
  CLI Version                 = 5.1.1
  node-appc Version           = 0.2.44
``` 
But again: the ti.imagefactory linked above is not using `ExifInterface` so I'm not sure why you have this error

**Comment by linron** [comment]
Thanks for your effort! It seems to be a problem with another module i am using.
